repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 73c2d77a42a113aee9e4b748c24937f09557b82d # 0.11.24
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 745be0411e3c150e246d527e531e5a221b8c3462 # v0.15.19
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format
